package com.cloud.cloudproviderpament.mapper;

import com.cloud.cloudproviderpament.entity.PfCombElementEvent;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface PfCombElementEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_comb_element_event
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_comb_element_event
     *
     * @mbggenerated
     */
    int insert(PfCombElementEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_comb_element_event
     *
     * @mbggenerated
     */
    int insertSelective(PfCombElementEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_comb_element_event
     *
     * @mbggenerated
     */
    PfCombElementEvent selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_comb_element_event
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PfCombElementEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_comb_element_event
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PfCombElementEvent record);

    List<PfCombElementEvent> selectAll(@Param("record") PfCombElementEvent record);
}