server:
  port: 8066

spring:
  application: cloud-provider-pament0411

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://101.200.54.163:3306/neu_product?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: root
      password: neusoft@qaz
      initialSize: 1
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      #aop-patterns: com.marchsoft.admin.* # 配置要扫描的包
      filters: stat,wall # 配置监控防火墙

      stat-view-servlet: # 开启了statViewServlet功能,也就是监控页的配置
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false

      web-stat-filter: # 监控web应用，开启web监控功能
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      filter:
        stat:
          slow-sql-millis: 1000 #设置所有超过1000行的查询都是慢查询
          logSlowSql: true
          enabled: true
        wall: #开启防火墙的功能
          enabled: true
          config:
            drop-table-allow: false

  servlet:
    multipart:
        #上传一个文件最大值  默认是1MB
    max-file-size: 10MB
        #上传多个文件最大值  默认是10MB
    max-request-size: 100MB

jdbc:
  dialect: MySQL

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cloud.cloudproviderpament.entity
  configuration:
    mapUnderscoreToCamelCase: true # 开启驼峰命名转换法

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
  page-size-zero: true
