server:
  port: 8066

spring:
  application: cloud-provider-pament0411

  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://101.200.54.163:3306/ry-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: neusoft@qaz
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
          enabled: true
      statViewServlet:
          enabled: true
          # 设置白名单，不填则允许所有访问
          #allow:
          url-pattern: /druid/*
          # 控制台管理用户名和密码
          login-username: admin
          login-password: admin
#      filter:
#          stat:
#              enabled: true
#              # 慢SQL记录
#              log-slow-sql: true
#              slow-sql-millis: 1000
#              merge-sql: true
#          wall:
#              config:
#                  multi-statement-allow: true

  servlet:
    multipart:
        #上传一个文件最大值  默认是1MB
    max-file-size: 10MB
        #上传多个文件最大值  默认是10MB
    max-request-size: 100MB

jdbc:
  dialect: MySQL



