package com.cloud.cloudproviderpament.entity;

import java.io.Serializable;

public class PfCombElementEvent implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_comb_element_event.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_comb_element_event.ele_id
     *
     * @mbggenerated
     */
    private String eleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_comb_element_event.event_name
     *
     * @mbggenerated
     */
    private String eventName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_comb_element_event.event_sourcecode
     *
     * @mbggenerated
     */
    private String eventSourcecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pf_comb_element_event
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_comb_element_event.id
     *
     * @return the value of pf_comb_element_event.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_comb_element_event.id
     *
     * @param id the value for pf_comb_element_event.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_comb_element_event.ele_id
     *
     * @return the value of pf_comb_element_event.ele_id
     *
     * @mbggenerated
     */
    public String getEleId() {
        return eleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_comb_element_event.ele_id
     *
     * @param eleId the value for pf_comb_element_event.ele_id
     *
     * @mbggenerated
     */
    public void setEleId(String eleId) {
        this.eleId = eleId == null ? null : eleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_comb_element_event.event_name
     *
     * @return the value of pf_comb_element_event.event_name
     *
     * @mbggenerated
     */
    public String getEventName() {
        return eventName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_comb_element_event.event_name
     *
     * @param eventName the value for pf_comb_element_event.event_name
     *
     * @mbggenerated
     */
    public void setEventName(String eventName) {
        this.eventName = eventName == null ? null : eventName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_comb_element_event.event_sourcecode
     *
     * @return the value of pf_comb_element_event.event_sourcecode
     *
     * @mbggenerated
     */
    public String getEventSourcecode() {
        return eventSourcecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_comb_element_event.event_sourcecode
     *
     * @param eventSourcecode the value for pf_comb_element_event.event_sourcecode
     *
     * @mbggenerated
     */
    public void setEventSourcecode(String eventSourcecode) {
        this.eventSourcecode = eventSourcecode == null ? null : eventSourcecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_comb_element_event
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PfCombElementEvent other = (PfCombElementEvent) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getEleId() == null ? other.getEleId() == null : this.getEleId().equals(other.getEleId()))
            && (this.getEventName() == null ? other.getEventName() == null : this.getEventName().equals(other.getEventName()))
            && (this.getEventSourcecode() == null ? other.getEventSourcecode() == null : this.getEventSourcecode().equals(other.getEventSourcecode()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_comb_element_event
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getEleId() == null) ? 0 : getEleId().hashCode());
        result = prime * result + ((getEventName() == null) ? 0 : getEventName().hashCode());
        result = prime * result + ((getEventSourcecode() == null) ? 0 : getEventSourcecode().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_comb_element_event
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", eleId=").append(eleId);
        sb.append(", eventName=").append(eventName);
        sb.append(", eventSourcecode=").append(eventSourcecode);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}